In [1]:
import pandas as pd
import numpy as np

In [3]:
data_path = 'C:/Users/gufer/OneDrive/Documentos/Cumbuca/aula_04/data/campeonato-brasileiro-cartoes.csv'
data = pd.read_csv(data_path)
data.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
1,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
2,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72
3,4608,1,Vitoria,Amarelo,Marcelo Machado dos Santos,29.0,NaN,86
4,4608,1,Vitoria,Amarelo,Mansur,NaN,Zagueiro,10